CREATE DATABASE IF NOT EXISTS TRIGGERS_DB;

USE TRIGGERS_DB;

CREATE TABLE IF NOT EXISTS EMPLOYEES (
	ID INT AUTO_INCREMENT PRIMARY KEY, 
    EMPLOYEE_NAME VARCHAR(100),
    POSITION VARCHAR(100), 
    SALARY DECIMAL(10,2)
);

INSERT INTO EMPLOYEES (EMPLOYEE_NAME, POSITION, SALARY) VALUES('KARAN SHAH', 'CEO', 30000);

SELECT * FROM EMPLOYEES; 

# IN OUR COMPANY THERE ARE NO EMPLOYEES WITH SALARY LESS THAN 35000 
# WRITE A CODE WHICH WILL MAKE SURE THAT NO EMPLOTEE IS HAVING SALARY LESS THAN 35000 WHILE INSERTION
# BEFORE INSERT - TRIGGER TYPE 
DELIMITER &&
CREATE TRIGGER BEFORE_INSERTING_INTO_EMPLOYEES
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
	IF NEW.SALARY < 35000 THEN 
		SET NEW.SALARY = 35000;
	END IF;
END &&;
DELIMITER ;


CREATE TABLE IF NOT EXISTS EMPLOYEE_LOG (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    TABLENAME VARCHAR(100),
    ACTION_TYPE VARCHAR(100),
    EMP_ID INT,
    EMPLOYEE_NAME VARCHAR(100),
    OLD_SALARY DECIMAL(10, 2),
    NEW_SALARY DECIMAL(10, 2),
    LOG_TIME DATETIME
);

INSERT INTO EMPLOYEES (EMPLOYEE_NAME, POSITION, SALARY) VALUES('KARAN SHAH', 'CEO', 30000);
# TRIGGER TO INSERT THE LOGS INTO THE LOG TABLE AFTER THE CONDITION IS MET 
DELIMITER &&
CREATE TRIGGER AFTER_INSERT_LOG_OPERATION1
AFTER INSERT ON EMPLOYEES
FOR EACH ROW 
BEGIN 
	INSERT INTO EMPLOYEE_LOG (ACTION_TYPE, TABLENAME, EMP_ID, EMPLOYEE_NAME, OLD_SALARY, NEW_SALARY, LOG_TIME)
    VALUES ('INSERT', 'EMPLOYEES', NEW.ID, NEW.EMPLOYEE_NAME, 0, NEW.SALARY, NOW());
END &&;
DELIMITER ;


INSERT INTO EMPLOYEES (EMPLOYEE_NAME, POSITION, SALARY) VALUES('KARAN SHAH', 'CEO', 30000);
INSERT INTO EMPLOYEES (EMPLOYEE_NAME, POSITION, SALARY) VALUES('Anand Jha', 'CFO', 25000);
INSERT INTO EMPLOYEES (EMPLOYEE_NAME, POSITION, SALARY) VALUES('Ram', 'BI Dev', 40000);

SELECT * FROM EMPLOYEES;

select * from employee_log;


# BEFORE UPDATE - PERSON CANNOT CHANGE THE SALARY TO LESS THAN 35000 
DELIMITER &&
CREATE TRIGGER BEFORE_UPDATING_INTO_EMPLOYEES
BEFORE UPDATE ON EMPLOYEES
FOR EACH ROW
BEGIN
	IF NEW.SALARY < 35000 THEN 
		SET NEW.SALARY = 35000;
	END IF;
END &&;
DELIMITER ;

# AFTER UPDATE 
DELIMITER &&
CREATE TRIGGER AFTER_UPDATE_LOG_OPERATION
AFTER UPDATE ON EMPLOYEES
FOR EACH ROW 
BEGIN 
	INSERT INTO EMPLOYEE_LOG (ACTION_TYPE, TABLENAME, EMP_ID, EMPLOYEE_NAME, OLD_SALARY, NEW_SALARY, LOG_TIME)
    VALUES ('UPDATE', 'EMPLOYEES', NEW.ID, NEW.EMPLOYEE_NAME, OLD.SALARY, NEW.SALARY, NOW());
END &&;
DELIMITER ;



# UPDATE 
UPDATE EMPLOYEES SET SALARY = 40000 WHERE EMPLOYEE_NAME = 'KARAN SHAH';

SELECT * FROM EMPLOYEES;

select * from employee_log;


# Delete Operation 
# Back up Table
CREATE TABLE IF NOT EXISTS EMPLOYEES_BAK (
	ID INT AUTO_INCREMENT PRIMARY KEY, 
    EMPLOYEE_NAME VARCHAR(100),
    POSITION VARCHAR(100), 
    SALARY DECIMAL(10,2)
);

SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES_BAK;

DELETE FROM EMPLOYEES
WHERE ID = 3;

# BEFORE DELETE 
# EMPLOYEE TABLE #BACK # LOG 
DELIMITER $$
CREATE TRIGGER before_delete_operation
BEFORE DELETE ON EMPLOYEES
FOR EACH ROW 
BEGIN
	INSERT INTO EMPLOYEES_BAK(ID, EMPLOYEE_NAME, POSITION, SALARY)
    VALUES(OLD.id, OLD.EMPLOYEE_NAME, OLD.POSITION, OLD.SALARY);
	INSERT INTO EMPLOYEE_LOG (ACTION_TYPE, TABLENAME, EMP_ID, EMPLOYEE_NAME, OLD_SALARY, NEW_SALARY, LOG_TIME)
    VALUES ('INSERT', 'EMPLOYEES_BACK', OLD.ID, OLD.EMPLOYEE_NAME, OLD.SALARY, OLD.SALARY, NOW());
END$$
DELIMITER ;

-> Ajj date -> yesterdays date -> delete -> month end tak -> 34000


# BEFORE DELETE 
# EMPLOYEE TABLE #BACK # LOG 
DELIMITER $$
CREATE TRIGGER after_delete_operation
AFTER DELETE ON EMPLOYEES
FOR EACH ROW 
BEGIN
    INSERT INTO EMPLOYEE_LOG (ACTION_TYPE, TABLENAME, EMP_ID, EMPLOYEE_NAME, OLD_SALARY, NEW_SALARY, LOG_TIME)
    VALUES ('DELETE', 'EMPLOYEES', OLD.ID, OLD.EMPLOYEE_NAME, OLD.SALARY, OLD.SALARY, NOW());
END$$
DELIMITER ;




INSERT INTO EMPLOYEES (EMPLOYEE_NAME, POSITION, SALARY) VALUES('Aakash Yadav', 'BI Dev', 40000);
INSERT INTO EMPLOYEES (EMPLOYEE_NAME, POSITION, SALARY) VALUES('Nakul Mehta', 'SQL Dev', 43000);
INSERT INTO EMPLOYEES (EMPLOYEE_NAME, POSITION, SALARY) VALUES('Vinod', 'Database Architect', 35000);

SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES_BAK;
SELECT * FROM EMPLOYEE_LOG
ORDER BY LOG_TIME DESC;

DELETE FROM EMPLOYEES 
WHERE ID = 2;
DELETE FROM EMPLOYEES 
WHERE ID = 2;
DELETE FROM EMPLOYEES 
WHERE ID = 2;
DELETE FROM EMPLOYEES 
WHERE ID = 2;
DELETE FROM EMPLOYEES 
WHERE ID = 2;
DELETE FROM EMPLOYEES 
WHERE ID = 2;
DELETE FROM EMPLOYEES 
WHERE ID = 2;
DELETE FROM EMPLOYEES 
WHERE ID = 2;
DELETE FROM EMPLOYEES 
WHERE ID = 2;



