create or replace TABLE DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_CTRL (
	PROCESS_NAME VARCHAR(16777216) NOT NULL,
	LAST_RUN_TS TIMESTAMP_NTZ(9),
	primary key (PROCESS_NAME)
);

create or replace TABLE DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_AGG (
	TABLE_ID NUMBER(38,0),
	TABLE_NAME VARCHAR(16777216),
	TB_SCHEMA_NAME VARCHAR(100),
	TB_DATABASE_NAME VARCHAR(100),
	OWNER_NAME VARCHAR(100),
	RECORD_COUNT NUMBER(38,0),
	RETENTION_TIME NUMBER(38,0),
	CREATED TIMESTAMP_LTZ(6),
	LAST_ALTERED TIMESTAMP_LTZ(6),
	LAST_DDL TIMESTAMP_LTZ(6),
	LAST_DDL_BY VARCHAR(100),
	ACTIVE_BYTES NUMBER(38,0),
	TIME_TRAVEL_BYTES NUMBER(38,0),
	FAILSAFE_BYTES NUMBER(38,0),
	TAG_NAME VARCHAR(100),
	TAG_VALUE VARCHAR(100),
	COLUMN_NAME VARCHAR(100),
	POLICY_ID NUMBER(38,0),
	POLICY_NAME VARCHAR(100),
	POLICY_KIND VARCHAR(100),
	REF_COLUMN_NAME VARCHAR(100),
	REF_ARG_COLUMN_NAMES VARCHAR(100),
	MASKING_POLICY_BODY VARCHAR(16777216),
	PROJECTION_POLICY_BODY VARCHAR(16777216),
	ROW_ACCESS_POLICY_BODY VARCHAR(16777216),
	DEPENDENT_DATABASE VARCHAR(100),
	DEPENDENT_SCHEMA VARCHAR(100),
	DEPENDENT_OBJECT_NAME VARCHAR(100),
	DEPENDENT_OBJECT_DOMAIN VARCHAR(100),
	DEPENDENT_COLUMN VARCHAR(100),
	TABLE_DESCRIPTION VARCHAR(16777216),
	COLUMN_DESCRIPTION VARCHAR(16777216)
);

create or replace TABLE DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_RPT (
	TABLE_ID NUMBER(38,0),
	TABLE_NAME VARCHAR(200),
	TB_SCHEMA_NAME VARCHAR(100),
	TB_DATABASE_NAME VARCHAR(100),
	OWNER_NAME VARCHAR(100),
	RECORD_COUNT NUMBER(38,0),
	RETENTION_TIME NUMBER(38,0),
	CREATED TIMESTAMP_LTZ(6),
	LAST_ALTERED TIMESTAMP_LTZ(6),
	LAST_DDL TIMESTAMP_LTZ(6),
	LAST_DDL_BY VARCHAR(100),
	ACTIVE_BYTES NUMBER(38,0),
	TIME_TRAVEL_BYTES NUMBER(38,0),
	FAILSAFE_BYTES NUMBER(38,0),
	TAG_NAME VARCHAR(100),
	TAG_VALUE VARCHAR(100),
	COLUMN_NAME VARCHAR(100),
	POLICY_ID NUMBER(38,0),
	POLICY_NAME VARCHAR(100),
	POLICY_KIND VARCHAR(100),
	REF_COLUMN_NAME VARCHAR(100),
	REF_ARG_COLUMN_NAMES VARCHAR(100),
	MASKING_POLICY_BODY VARCHAR(300),
	PROJECTION_POLICY_BODY VARCHAR(300),
	ROW_ACCESS_POLICY_BODY VARCHAR(16384),
	DEPENDENT_DATABASE VARCHAR(100),
	DEPENDENT_SCHEMA VARCHAR(100),
	DEPENDENT_OBJECT_NAME VARCHAR(100),
	DEPENDENT_OBJECT_DOMAIN VARCHAR(100),
	DEPENDENT_COLUMN VARCHAR(100),
	INSERT_TS TIMESTAMP_LTZ(6),
	UPDATE_TS TIMESTAMP_LTZ(6),
	COMMENTS VARCHAR(300),
	TABLE_DESCRIPTION VARCHAR(16777216),
	COLUMN_DESCRIPTION VARCHAR(16777216)
);

CREATE OR REPLACE PROCEDURE DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_MOD()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    v_last_run_ts TIMESTAMP_NTZ;
BEGIN

    -- 1. Get the last run timestamp
    SELECT COALESCE(MAX(LAST_RUN_TS), ''2000-01-01''::TIMESTAMP_NTZ)
    INTO v_last_run_ts
    FROM DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_CTRL
    WHERE PROCESS_NAME = ''UPDATE_GOVERNANCE_METADATA'';

    -- 2. Clean staging table
    DELETE FROM DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_AGG;

    -- 3. Load table metadata
    INSERT INTO DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_AGG (
        TABLE_ID, TABLE_NAME, TB_SCHEMA_NAME, TB_DATABASE_NAME,
        OWNER_NAME, RECORD_COUNT, RETENTION_TIME, CREATED,
        LAST_ALTERED, LAST_DDL, LAST_DDL_BY,
        ACTIVE_BYTES, TIME_TRAVEL_BYTES, FAILSAFE_BYTES
    )
    SELECT
        t.TABLE_ID, t.TABLE_NAME, t.TABLE_SCHEMA, t.TABLE_CATALOG,
        t.TABLE_OWNER, t.ROW_COUNT, t.RETENTION_TIME, t.CREATED,
        t.LAST_ALTERED, t.LAST_DDL, t.LAST_DDL_BY,
        ts.ACTIVE_BYTES, ts.TIME_TRAVEL_BYTES, ts.FAILSAFE_BYTES
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES t
    LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS ts
        ON t.TABLE_ID = ts.ID
        AND t.TABLE_CATALOG = ts.TABLE_CATALOG
        AND t.TABLE_SCHEMA = ts.TABLE_SCHEMA
        AND t.TABLE_NAME = ts.TABLE_NAME
    WHERE t.DELETED IS NULL
      AND (t.CREATED > v_last_run_ts OR t.LAST_ALTERED > v_last_run_ts);

    -- 4. Update tag references
    UPDATE DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_AGG agg
    SET TAG_NAME = tr.TAG_NAME,
        TAG_VALUE = tr.TAG_VALUE,
        COLUMN_NAME = tr.COLUMN_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES tr
    WHERE agg.TABLE_NAME = tr.OBJECT_NAME
      AND agg.TB_SCHEMA_NAME = tr.OBJECT_SCHEMA
      AND agg.TB_DATABASE_NAME = tr.OBJECT_DATABASE;

    -- 5. Update policy references
    UPDATE agg
    SET MASKING_POLICY = pr.POLICY_NAME,
        MASKING_POLICY_SIGNATURE = pr.POLICY_SIGNATURE,
        POLICY_KIND = pr.POLICY_KIND
    FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES pr
    WHERE agg.TABLE_NAME = pr.OBJECT_NAME
      AND agg.TB_SCHEMA_NAME = pr.OBJECT_SCHEMA
      AND agg.TB_DATABASE_NAME = pr.OBJECT_DATABASE;

    -- 6. Update projection policy info
    UPDATE agg
    SET PROJECTION_POLICY_NAME = prj.PROJECTION_POLICY_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES t
    JOIN LATERAL FLATTEN(input => t.TABLE_OPTIONS) f
        ON f.KEY = ''PROJECTION_POLICY''
    JOIN (
        SELECT TABLE_ID, VALUE::STRING AS PROJECTION_POLICY_NAME
        FROM LATERAL FLATTEN(
            input => (SELECT TABLE_OPTIONS FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES)
        )
        WHERE KEY = ''PROJECTION_POLICY''
    ) prj ON prj.TABLE_ID = t.TABLE_ID
    WHERE agg.TABLE_ID = t.TABLE_ID;

 CREATE OR REPLACE TEMP TABLE TEMP_CORTEX_DESC AS
    SELECT
        TABLE_ID,
        TABLE_NAME,
        COLUMN_NAME,
        SNOWFLAKE.CORTEX.COMPLETE(
            ''llama2-70b-chat'',
            ''You are a metadata assistant. Based on the table name "'' || TABLE_NAME || ''", generate a concise and meaningful one-sentence business description of what this table likely stores or represents. Do not include the table name in your response.''
        ) AS TABLE_DESCRIPTION,
        CASE 
            WHEN COLUMN_NAME IS NOT NULL THEN SNOWFLAKE.CORTEX.COMPLETE(
                ''llama2-70b-chat'',
                ''You are a metadata assistant. Based on the column name "'' || COLUMN_NAME || ''" in the table "'' || TABLE_NAME || ''", describe what kind of data this column likely holds and its potential business meaning. Do not mention the column or table name in your response.''
            )
        END AS COLUMN_DESCRIPTION
    FROM DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_AGG;

    -- 8. Update AGG table with Cortex descriptions
    UPDATE DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_AGG agg
    SET TABLE_DESCRIPTION = c.TABLE_DESCRIPTION,
        COLUMN_DESCRIPTION = c.COLUMN_DESCRIPTION
    FROM TEMP_CORTEX_DESC c
    WHERE agg.TABLE_ID = c.TABLE_ID
      AND agg.TABLE_NAME = c.TABLE_NAME
      AND (agg.COLUMN_NAME IS NULL OR agg.COLUMN_NAME = c.COLUMN_NAME);

    -- 9. Merge into reporting table
    MERGE INTO DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_RPT tgt
    USING DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_AGG src
    ON tgt.TABLE_ID = src.TABLE_ID
       AND tgt.COLUMN_NAME IS NOT DISTINCT FROM src.COLUMN_NAME
    WHEN MATCHED THEN UPDATE SET
        TABLE_NAME = src.TABLE_NAME,
        TB_SCHEMA_NAME = src.TB_SCHEMA_NAME,
        TB_DATABASE_NAME = src.TB_DATABASE_NAME,
        OWNER_NAME = src.OWNER_NAME,
        RECORD_COUNT = src.RECORD_COUNT,
        RETENTION_TIME = src.RETENTION_TIME,
        CREATED = src.CREATED,
        LAST_ALTERED = src.LAST_ALTERED,
        LAST_DDL = src.LAST_DDL,
        LAST_DDL_BY = src.LAST_DDL_BY,
        ACTIVE_BYTES = src.ACTIVE_BYTES,
        TIME_TRAVEL_BYTES = src.TIME_TRAVEL_BYTES,
        FAILSAFE_BYTES = src.FAILSAFE_BYTES,
        TAG_NAME = src.TAG_NAME,
        TAG_VALUE = src.TAG_VALUE,
        MASKING_POLICY = src.MASKING_POLICY,
        MASKING_POLICY_SIGNATURE = src.MASKING_POLICY_SIGNATURE,
        POLICY_KIND = src.POLICY_KIND,
        PROJECTION_POLICY_NAME = src.PROJECTION_POLICY_NAME,
        TABLE_DESCRIPTION = src.TABLE_DESCRIPTION,
        COLUMN_DESCRIPTION = src.COLUMN_DESCRIPTION
    WHEN NOT MATCHED THEN INSERT (
        TABLE_ID, TABLE_NAME, TB_SCHEMA_NAME, TB_DATABASE_NAME,
        OWNER_NAME, RECORD_COUNT, RETENTION_TIME, CREATED,
        LAST_ALTERED, LAST_DDL, LAST_DDL_BY,
        ACTIVE_BYTES, TIME_TRAVEL_BYTES, FAILSAFE_BYTES,
        TAG_NAME, TAG_VALUE, COLUMN_NAME,
        MASKING_POLICY, MASKING_POLICY_SIGNATURE, POLICY_KIND,
        PROJECTION_POLICY_NAME, TABLE_DESCRIPTION, COLUMN_DESCRIPTION
    )
    VALUES (
        src.TABLE_ID, src.TABLE_NAME, src.TB_SCHEMA_NAME, src.TB_DATABASE_NAME,
        src.OWNER_NAME, src.RECORD_COUNT, src.RETENTION_TIME, src.CREATED,
        src.LAST_ALTERED, src.LAST_DDL, src.LAST_DDL_BY,
        src.ACTIVE_BYTES, src.TIME_TRAVEL_BYTES, src.FAILSAFE_BYTES,
        src.TAG_NAME, src.TAG_VALUE, src.COLUMN_NAME,
        src.MASKING_POLICY, src.MASKING_POLICY_SIGNATURE, src.POLICY_KIND,
        src.PROJECTION_POLICY_NAME, src.TABLE_DESCRIPTION, src.COLUMN_DESCRIPTION
    );

    -- 10. Update control table with new run timestamp
    MERGE INTO DATA_GOVERNANCE.SNOWFLAKE.GOVERNANCE_METADATA_CTRL tgt
    USING (
        SELECT ''UPDATE_GOVERNANCE_METADATA'' AS PROCESS_NAME,
               CURRENT_TIMESTAMP() AS LAST_RUN_TS
    ) src
    ON tgt.PROCESS_NAME = src.PROCESS_NAME
    WHEN MATCHED THEN UPDATE SET LAST_RUN_TS = src.LAST_RUN_TS
    WHEN NOT MATCHED THEN INSERT (PROCESS_NAME, LAST_RUN_TS)
    VALUES (src.PROCESS_NAME, src.LAST_RUN_TS);

    RETURN ''Governance metadata update completed.'';

END;
';
