CREATE OR REPLACE PROCEDURE SNOWFLAKE_CORTEX_BASED_QUERY_OPTIMIZER.APP_SCHEMA.SP_MOST_EXPENSIVE_QUERY_NODES("QUERY_ID" VARCHAR)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
RS RESULTSET;
BEGIN
RS:=(
SELECT PATH,VALUE FROM (
SELECT * from 
(
select 
OBJECT_CONSTRUCT(''QUERY_ID'',:QUERY_ID,''OPERATOR_TYPE'',OPERATOR_TYPE,''OPERATOR_STATISTICS'',OPERATOR_STATISTICS,''EXECUTION_TIME_BREAKDOWN'',EXECUTION_TIME_BREAKDOWN,''OPERATOR_ATTRIBUTES'',OPERATOR_ATTRIBUTES
)AS MOST_EXPENSIVE
,RANK()OVER(PARTITION BY :QUERY_ID ORDER BY  EXECUTION_TIME_BREAKDOWN:overall_percentage DESC) AS RNK
from table(get_query_operator_stats(:QUERY_ID))
)
where
RNK =1
), LATERAL FLATTEN(MOST_EXPENSIVE,RECURSIVE=>TRUE,OUTER=>TRUE)
WHERE TYPEOF(VALUE) NOT IN (''OBJECT'',''ARRAY'')
);
RETURN TABLE(RS);
END;
';
